---
report_description: 'Retention and churn rates by user cohort. For details, see: https://help.modeanalytics.com/articles/cohort-analysis-for-customer-retention-and-churn-rate/'
is_full_width: false
hide_run_button: false
