---
report_description: 'Feature use over time, by the number of times the feature has
  been used and by how many people. For details, see: https://modeanalytics.zendesk.com/hc/en-us/articles/203326184'
is_full_width: false
hide_run_button: false
